gha: rerun workflow after AWS creds injected (#35)
in the circleCI pipeline it does not run until makefile sets up webhooks
but in GHA it runs as soon as zero create pushes the repo, during that
time it has no AWS credentials, so it will always fail

diff --git a/templates/.github/workflows/ci.yml b/templates/.github/workflows/ci.yml
--- a/templates/.github/workflows/ci.yml
+++ b/templates/.github/workflows/ci.yml
@@ -7,7 +7,7 @@ jobs:
     runs-on: ubuntu-latest
     env:
       CI: true
-      build_env: production
+      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
     steps:
     - uses: actions/checkout@v2
     - name: Run Unit Tests
@@ -17,6 +17,10 @@ jobs:
     - run: |
         yarn
         yarn test --watchAll=false
+    - if: env.AWS_ACCESS_KEY_ID == null
+          run: |
+            echo "AWS Credentials not found, This is expected for the first run as the repo is provisioned then secrets are injected at a later step."
+            exit 1
   build:
       needs: unit-test
       runs-on: ubuntu-latest
